version: '3.8'

services:
  db:
    image: mysql:8.0.33
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: db_users
      MYSQL_ROOT_PASSWORD: superadmin1234
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'

  app:
    build: .
    container_name: spring-app
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: superadmin1234
